import { CATEGORY_GROUPS } from "./catalogue";
import type {
  Announcement,
  Badge,
  Competition,
  ContestantApplication,
  PublicContestant,
  Sponsor,
} from "./types";
import { buildJourney } from "./competition";

/**
 * Launch competition configuration.
 *
 * Everything here is configuration data that will move into the database as a
 * seed migration once the backend is connected. No screen hard-codes any of it.
 */

const YEAR = 2026;

export const COMPETITIONS: Competition[] = [
  {
    id: "cmp_zgt_season_one",
    slug: "season-one",
    name: `Zik's Got Talent ${YEAR}`,
    tagline: "Your talent deserves to be discovered.",
    description:
      "A national, multi-category talent search for singers, rappers, dancers, comedians, designers, photographers, animators, coders and creators. One season. Thousands of entries. One winner — and a creative identity that outlives the competition.",
    coverImageAlt: "Contestant lit by a single gold spotlight on a dark stage",
    status: "REGISTRATION_OPEN",
    startsAt: `${YEAR}-09-01T00:00:00.000Z`,
    endsAt: `${YEAR}-12-20T00:00:00.000Z`,
    registrationOpensAt: `${YEAR}-08-01T00:00:00.000Z`,
    registrationClosesAt: `${YEAR}-10-15T23:59:00.000Z`,
    eligibility: [
      "Open to individuals aged 16 and above.",
      "Entrants under 18 require verified guardian consent.",
      "One application per person per season.",
      "Audition material must be your own original work or properly licensed.",
    ],
    rules: [
      "One application per person, per season. Duplicate applications are removed.",
      "Audition media must be unedited for performance categories unless the category brief states otherwise.",
      "Any form of vote manipulation results in immediate disqualification.",
      "Judges' scores are final within a round unless an integrity review is opened by an admin.",
      "Contestants keep ownership of their work; the competition receives a licence to feature approved media.",
    ],
    consentRequirements: [
      "I confirm the audition material is my own original work or properly licensed.",
      "I consent to my approved media being featured across Zik's Got Talent channels.",
      "I understand my registration creates or connects a free ArtistrySynk creative profile.",
      "I accept the competition rules, eligibility criteria and privacy policy.",
    ],
    rounds: [
      {
        id: "rnd_registration",
        competitionId: "cmp_zgt_season_one",
        slug: "registration",
        name: "Registration",
        sequence: 1,
        description: "Choose your category, create your identity and open your application.",
        opensAt: `${YEAR}-08-01T00:00:00.000Z`,
        closesAt: `${YEAR}-10-15T23:59:00.000Z`,
        advancementRule: "AUTOMATIC",
        isActive: true,
      },
      {
        id: "rnd_review",
        competitionId: "cmp_zgt_season_one",
        slug: "application-review",
        name: "Application Review",
        sequence: 2,
        description: "Moderators verify eligibility and audition material.",
        opensAt: `${YEAR}-08-15T00:00:00.000Z`,
        closesAt: `${YEAR}-10-25T23:59:00.000Z`,
        advancementRule: "MANUAL",
        isActive: true,
      },
      {
        id: "rnd_audition",
        competitionId: "cmp_zgt_season_one",
        slug: "audition",
        name: "Audition",
        sequence: 3,
        description: "Judges review submitted auditions per category.",
        opensAt: `${YEAR}-10-26T00:00:00.000Z`,
        closesAt: `${YEAR}-11-05T23:59:00.000Z`,
        advancementRule: "SCORE_THRESHOLD",
        isActive: true,
      },
      {
        id: "rnd_top_100",
        competitionId: "cmp_zgt_season_one",
        slug: "top-100",
        name: "Top 100",
        sequence: 4,
        description: "The first national shortlist.",
        opensAt: null,
        closesAt: null,
        advancementRule: "TOP_N:100",
        isActive: true,
      },
      {
        id: "rnd_top_50",
        competitionId: "cmp_zgt_season_one",
        slug: "top-50",
        name: "Top 50",
        sequence: 5,
        description: "Category semi-finals.",
        opensAt: null,
        closesAt: null,
        advancementRule: "TOP_N:50",
        isActive: true,
      },
      {
        id: "rnd_top_20",
        competitionId: "cmp_zgt_season_one",
        slug: "top-20",
        name: "Top 20",
        sequence: 6,
        description: "Live rounds begin. Public voting opens.",
        opensAt: null,
        closesAt: null,
        advancementRule: "TOP_N:20",
        isActive: true,
      },
      {
        id: "rnd_top_10",
        competitionId: "cmp_zgt_season_one",
        slug: "top-10",
        name: "Top 10",
        sequence: 7,
        description: "The final stretch.",
        opensAt: null,
        closesAt: null,
        advancementRule: "TOP_N:10",
        isActive: true,
      },
      {
        id: "rnd_final",
        competitionId: "cmp_zgt_season_one",
        slug: "final",
        name: "Final",
        sequence: 8,
        description: "The finale, judged live with a hybrid public vote.",
        opensAt: null,
        closesAt: null,
        advancementRule: "TOP_N:3",
        isActive: true,
      },
      {
        id: "rnd_winner",
        competitionId: "cmp_zgt_season_one",
        slug: "winner",
        name: "Winner",
        sequence: 9,
        description: "One winner announced.",
        opensAt: null,
        closesAt: null,
        advancementRule: "TOP_N:1",
        isActive: true,
      },
    ],
    categoryGroupIds: CATEGORY_GROUPS.map((g) => g.id),
    scoringCriteria: [
      {
        id: "crt_talent",
        competitionId: "cmp_zgt_season_one",
        name: "Talent",
        maxScore: 10,
        weight: 25,
        sortOrder: 1,
        isActive: true,
      },
      {
        id: "crt_creativity",
        competitionId: "cmp_zgt_season_one",
        name: "Creativity",
        maxScore: 10,
        weight: 20,
        sortOrder: 2,
        isActive: true,
      },
      {
        id: "crt_originality",
        competitionId: "cmp_zgt_season_one",
        name: "Originality",
        maxScore: 10,
        weight: 20,
        sortOrder: 3,
        isActive: true,
      },
      {
        id: "crt_presence",
        competitionId: "cmp_zgt_season_one",
        name: "Stage Presence",
        maxScore: 10,
        weight: 15,
        sortOrder: 4,
        isActive: true,
      },
      {
        id: "crt_technical",
        competitionId: "cmp_zgt_season_one",
        name: "Technical Ability",
        maxScore: 10,
        weight: 15,
        sortOrder: 5,
        isActive: true,
      },
      {
        id: "crt_overall",
        competitionId: "cmp_zgt_season_one",
        name: "Overall",
        maxScore: 10,
        weight: 5,
        sortOrder: 6,
        isActive: true,
      },
    ],
    voting: {
      model: "HYBRID",
      judgeWeight: 70,
      publicWeight: 30,
      opensAt: null,
      closesAt: null,
      votesPerUserPerDay: 3,
      requiresAuthentication: true,
      rateLimitPerMinute: 5,
    },
    stats: {
      entries: 0,
      categories: CATEGORY_GROUPS.reduce((sum, g) => sum + g.categories.length, 0),
      cities: 24,
      prizePool: "₦25M+",
    },
  },
];

export const SPONSORS: Sponsor[] = [
  {
    id: "spn_artistrysynk",
    name: "ArtistrySynk",
    tier: "MAJOR_SPONSOR",
    description:
      "The creative identity platform behind Zik's Got Talent. Every contestant leaves with an ArtistrySynk creative profile.",
    website: "https://artistrysynk.app",
    logoUrl: null,
    placements: ["HERO", "HEADER", "FOOTER", "SPONSOR_PAGE"],
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "spn_chow",
    name: "Chow",
    tier: "MAJOR_SPONSOR",
    description: "Fuelling the stage, the crew and the contestants across every round.",
    website: "https://example.com",
    logoUrl: null,
    placements: ["HERO", "FOOTER", "SPONSOR_PAGE"],
    sortOrder: 2,
    isActive: true,
  },
];

export const ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann_open",
    competitionId: "cmp_zgt_season_one",
    title: "Registration is open for Season One",
    body: "Applications are open across 22 categories in five groups. Registration closes 15 October — auditions are reviewed continuously, so early entries get earlier feedback.",
    publishedAt: `${YEAR}-08-01T09:00:00.000Z`,
    isPinned: true,
    audience: "PUBLIC",
  },
  {
    id: "ann_sponsors",
    competitionId: "cmp_zgt_season_one",
    title: "ArtistrySynk × Chow announced as major sponsors",
    body: "Season One is powered by ArtistrySynk and Chow, with supporting sponsors and media partners announced through the season.",
    publishedAt: `${YEAR}-08-04T12:00:00.000Z`,
    isPinned: false,
    audience: "PUBLIC",
  },
  {
    id: "ann_brief",
    competitionId: "cmp_zgt_season_one",
    title: "Audition briefs published per category",
    body: "Each category now has its own audition brief and length limit. Check your category page before you record.",
    publishedAt: `${YEAR}-08-08T15:30:00.000Z`,
    isPinned: false,
    audience: "CONTESTANTS",
  },
];

export const BADGES: Badge[] = [
  {
    id: "bdg_entrant",
    slug: "season-one-entrant",
    name: "Season One Entrant",
    description: "Completed a Season One application.",
  },
  {
    id: "bdg_top_100",
    slug: "top-100",
    name: "Top 100",
    description: "Selected for the first national shortlist.",
  },
  {
    id: "bdg_finalist",
    slug: "finalist",
    name: "Finalist",
    description: "Reached the Season One final.",
  },
  {
    id: "bdg_winner",
    slug: "winner",
    name: "Winner",
    description: "Winner of Zik's Got Talent.",
  },
];

export const PUBLIC_CONTESTANTS: PublicContestant[] = [
  {
    handle: "amaraokoye",
    displayName: "Amara Okoye",
    categoryName: "Singing",
    groupName: "Music",
    location: "Enugu, Nigeria",
    bio: "Afro-soul vocalist writing in Igbo and English. Choir-trained, club-tested.",
    stage: "Application Review",
    badges: ["Season One Entrant"],
    photoAlt: "Portrait of a young vocalist under warm stage light",
  },
  {
    handle: "kelechidraws",
    displayName: "Kelechi Nwosu",
    categoryName: "Digital Art",
    groupName: "Digital / Tech",
    location: "Lagos, Nigeria",
    bio: "Illustrator building Afro-futurist worlds one frame at a time.",
    stage: "Application Review",
    badges: ["Season One Entrant"],
    photoAlt: "Portrait of a digital artist beside a drawing tablet",
  },
  {
    handle: "stepbyzee",
    displayName: "Zainab Bello",
    categoryName: "Dance",
    groupName: "Performance",
    location: "Abuja, Nigeria",
    bio: "Street and contemporary fusion dancer. Crew captain, solo competitor.",
    stage: "Audition",
    badges: ["Season One Entrant"],
    photoAlt: "Dancer mid-movement in a rehearsal space",
  },
];

/** Demo private application used by the contestant dashboard shell. */
export const DEMO_APPLICATION: ContestantApplication = {
  id: "app_demo_0001",
  competitionId: "cmp_zgt_season_one",
  competitionName: COMPETITIONS[0]!.name,
  identityRef: "local_demo",
  handle: "amaraokoye",
  displayName: "Amara Okoye",
  categoryName: "Singing",
  groupName: "Music",
  status: "UNDER_REVIEW",
  currentRoundSlug: "application-review",
  journey: buildJourney(COMPETITIONS[0]!, "application-review"),
  submittedAt: `${YEAR}-08-12T18:22:00.000Z`,
  submissions: [
    {
      id: "sub_1",
      type: "VIDEO",
      title: "Audition — original song, live vocal",
      moderation: "APPROVED",
      createdAt: `${YEAR}-08-12T18:20:00.000Z`,
    },
    {
      id: "sub_2",
      type: "IMAGE",
      title: "Profile photo",
      moderation: "APPROVED",
      createdAt: `${YEAR}-08-12T18:21:00.000Z`,
    },
  ],
};
