/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as ArtistrysynkRouteImport } from './routes/artistrysynk'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as JudgeRouteImport } from './routes/judge'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackRouteImport } from './routes/track'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSectionRouteImport } from './routes/admin.$section'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminCompetitionsRouteImport } from './routes/admin.competitions'
import { Route as AdminJudgingRouteImport } from './routes/admin.judging'
import { Route as AdminLifecycleRouteImport } from './routes/admin.lifecycle'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminVotingRouteImport } from './routes/admin.voting'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as CompetitionsIndexRouteImport } from './routes/competitions.index'
import { Route as CompetitionsSlugRouteImport } from './routes/competitions.$slug'
import { Route as ContestantsIndexRouteImport } from './routes/contestants.index'
import { Route as ContestantsHandleRouteImport } from './routes/contestants.$handle'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSectionRouteImport } from './routes/dashboard.$section'
import { Route as OauthArtistrysynkReturnRouteImport } from './routes/oauth.artistrysynk.return'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistrysynkRoute = ArtistrysynkRouteImport.update({
  id: '/artistrysynk',
  path: '/artistrysynk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeRoute = JudgeRouteImport.update({
  id: '/judge',
  path: '/judge',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompetitionsRoute = AdminCompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJudgingRoute = AdminJudgingRouteImport.update({
  id: '/judging',
  path: '/judging',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLifecycleRoute = AdminLifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVotingRoute = AdminVotingRouteImport.update({
  id: '/voting',
  path: '/voting',
  getParentRoute: () => AdminRoute,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsIndexRoute = CompetitionsIndexRouteImport.update({
  id: '/competitions/',
  path: '/competitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsSlugRoute = CompetitionsSlugRouteImport.update({
  id: '/competitions/$slug',
  path: '/competitions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestantsIndexRoute = ContestantsIndexRouteImport.update({
  id: '/contestants/',
  path: '/contestants/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestantsHandleRoute = ContestantsHandleRouteImport.update({
  id: '/contestants/$handle',
  path: '/contestants/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSectionRoute = DashboardSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => DashboardRoute,
} as any)
const OauthArtistrysynkReturnRoute = OauthArtistrysynkReturnRouteImport.update({
  id: '/oauth/artistrysynk/return',
  path: '/oauth/artistrysynk/return',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/artistrysynk': typeof ArtistrysynkRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/judge': typeof JudgeRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/sponsors': typeof SponsorsRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/vote': typeof VoteRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/judging': typeof AdminJudgingRoute
  '/admin/lifecycle': typeof AdminLifecycleRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/voting': typeof AdminVotingRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/contestants/$handle': typeof ContestantsHandleRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/contestants/': typeof ContestantsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/oauth/artistrysynk/return': typeof OauthArtistrysynkReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/announcements': typeof AnnouncementsRoute
  '/artistrysynk': typeof ArtistrysynkRoute
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/judge': typeof JudgeRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/sponsors': typeof SponsorsRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/vote': typeof VoteRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/judging': typeof AdminJudgingRoute
  '/admin/lifecycle': typeof AdminLifecycleRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/voting': typeof AdminVotingRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/contestants/$handle': typeof ContestantsHandleRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/admin': typeof AdminIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/competitions': typeof CompetitionsIndexRoute
  '/contestants': typeof ContestantsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/oauth/artistrysynk/return': typeof OauthArtistrysynkReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/artistrysynk': typeof ArtistrysynkRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/judge': typeof JudgeRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/sponsors': typeof SponsorsRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/vote': typeof VoteRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/judging': typeof AdminJudgingRoute
  '/admin/lifecycle': typeof AdminLifecycleRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/voting': typeof AdminVotingRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/contestants/$handle': typeof ContestantsHandleRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/contestants/': typeof ContestantsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/oauth/artistrysynk/return': typeof OauthArtistrysynkReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/announcements'
    | '/artistrysynk'
    | '/auth'
    | '/dashboard'
    | '/how-it-works'
    | '/judge'
    | '/privacy'
    | '/register'
    | '/rules'
    | '/sponsors'
    | '/terms'
    | '/track'
    | '/vote'
    | '/admin/$section'
    | '/admin/applications'
    | '/admin/competitions'
    | '/admin/judging'
    | '/admin/lifecycle'
    | '/admin/submissions'
    | '/admin/voting'
    | '/categories/$slug'
    | '/competitions/$slug'
    | '/contestants/$handle'
    | '/dashboard/$section'
    | '/admin/'
    | '/categories/'
    | '/competitions/'
    | '/contestants/'
    | '/dashboard/'
    | '/oauth/artistrysynk/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/announcements'
    | '/artistrysynk'
    | '/auth'
    | '/how-it-works'
    | '/judge'
    | '/privacy'
    | '/register'
    | '/rules'
    | '/sponsors'
    | '/terms'
    | '/track'
    | '/vote'
    | '/admin/$section'
    | '/admin/applications'
    | '/admin/competitions'
    | '/admin/judging'
    | '/admin/lifecycle'
    | '/admin/submissions'
    | '/admin/voting'
    | '/categories/$slug'
    | '/competitions/$slug'
    | '/contestants/$handle'
    | '/dashboard/$section'
    | '/admin'
    | '/categories'
    | '/competitions'
    | '/contestants'
    | '/dashboard'
    | '/oauth/artistrysynk/return'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/announcements'
    | '/artistrysynk'
    | '/auth'
    | '/dashboard'
    | '/how-it-works'
    | '/judge'
    | '/privacy'
    | '/register'
    | '/rules'
    | '/sponsors'
    | '/terms'
    | '/track'
    | '/vote'
    | '/admin/$section'
    | '/admin/applications'
    | '/admin/competitions'
    | '/admin/judging'
    | '/admin/lifecycle'
    | '/admin/submissions'
    | '/admin/voting'
    | '/categories/$slug'
    | '/competitions/$slug'
    | '/contestants/$handle'
    | '/dashboard/$section'
    | '/admin/'
    | '/categories/'
    | '/competitions/'
    | '/contestants/'
    | '/dashboard/'
    | '/oauth/artistrysynk/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRoute
  ArtistrysynkRoute: typeof ArtistrysynkRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  JudgeRoute: typeof JudgeRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  RulesRoute: typeof RulesRoute
  SponsorsRoute: typeof SponsorsRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  VoteRoute: typeof VoteRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CompetitionsSlugRoute: typeof CompetitionsSlugRoute
  ContestantsHandleRoute: typeof ContestantsHandleRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
  ContestantsIndexRoute: typeof ContestantsIndexRoute
  OauthArtistrysynkReturnRoute: typeof OauthArtistrysynkReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artistrysynk': {
      id: '/artistrysynk'
      path: '/artistrysynk'
      fullPath: '/artistrysynk'
      preLoaderRoute: typeof ArtistrysynkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge': {
      id: '/judge'
      path: '/judge'
      fullPath: '/judge'
      preLoaderRoute: typeof JudgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$section': {
      id: '/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/competitions': {
      id: '/admin/competitions'
      path: '/competitions'
      fullPath: '/admin/competitions'
      preLoaderRoute: typeof AdminCompetitionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/judging': {
      id: '/admin/judging'
      path: '/judging'
      fullPath: '/admin/judging'
      preLoaderRoute: typeof AdminJudgingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lifecycle': {
      id: '/admin/lifecycle'
      path: '/lifecycle'
      fullPath: '/admin/lifecycle'
      preLoaderRoute: typeof AdminLifecycleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/voting': {
      id: '/admin/voting'
      path: '/voting'
      fullPath: '/admin/voting'
      preLoaderRoute: typeof AdminVotingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/competitions'
      fullPath: '/competitions/'
      preLoaderRoute: typeof CompetitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$slug': {
      id: '/competitions/$slug'
      path: '/competitions/$slug'
      fullPath: '/competitions/$slug'
      preLoaderRoute: typeof CompetitionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contestants/': {
      id: '/contestants/'
      path: '/contestants'
      fullPath: '/contestants/'
      preLoaderRoute: typeof ContestantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contestants/$handle': {
      id: '/contestants/$handle'
      path: '/contestants/$handle'
      fullPath: '/contestants/$handle'
      preLoaderRoute: typeof ContestantsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$section': {
      id: '/dashboard/$section'
      path: '/$section'
      fullPath: '/dashboard/$section'
      preLoaderRoute: typeof DashboardSectionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/oauth/artistrysynk/return': {
      id: '/oauth/artistrysynk/return'
      path: '/oauth/artistrysynk/return'
      fullPath: '/oauth/artistrysynk/return'
      preLoaderRoute: typeof OauthArtistrysynkReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminSectionRoute: typeof AdminSectionRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminCompetitionsRoute: typeof AdminCompetitionsRoute
  AdminJudgingRoute: typeof AdminJudgingRoute
  AdminLifecycleRoute: typeof AdminLifecycleRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminVotingRoute: typeof AdminVotingRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSectionRoute: AdminSectionRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminCompetitionsRoute: AdminCompetitionsRoute,
  AdminJudgingRoute: AdminJudgingRoute,
  AdminLifecycleRoute: AdminLifecycleRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminVotingRoute: AdminVotingRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardSectionRoute: typeof DashboardSectionRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSectionRoute: DashboardSectionRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRoute,
  ArtistrysynkRoute: ArtistrysynkRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  JudgeRoute: JudgeRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  RulesRoute: RulesRoute,
  SponsorsRoute: SponsorsRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  VoteRoute: VoteRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CompetitionsSlugRoute: CompetitionsSlugRoute,
  ContestantsHandleRoute: ContestantsHandleRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
  ContestantsIndexRoute: ContestantsIndexRoute,
  OauthArtistrysynkReturnRoute: OauthArtistrysynkReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
