/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as CompetitionsIndexRouteImport } from './routes/competitions.index'
import { Route as CompetitionsSlugRouteImport } from './routes/competitions.$slug'
import { Route as ContestantsIndexRouteImport } from './routes/contestants.index'
import { Route as ContestantsHandleRouteImport } from './routes/contestants.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsIndexRoute = CompetitionsIndexRouteImport.update({
  id: '/competitions/',
  path: '/competitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsSlugRoute = CompetitionsSlugRouteImport.update({
  id: '/competitions/$slug',
  path: '/competitions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestantsIndexRoute = ContestantsIndexRouteImport.update({
  id: '/contestants/',
  path: '/contestants/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestantsHandleRoute = ContestantsHandleRouteImport.update({
  id: '/contestants/$handle',
  path: '/contestants/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/sponsors': typeof SponsorsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/contestants/$handle': typeof ContestantsHandleRoute
  '/categories/': typeof CategoriesIndexRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/contestants/': typeof ContestantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/sponsors': typeof SponsorsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/contestants/$handle': typeof ContestantsHandleRoute
  '/categories': typeof CategoriesIndexRoute
  '/competitions': typeof CompetitionsIndexRoute
  '/contestants': typeof ContestantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/sponsors': typeof SponsorsRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/contestants/$handle': typeof ContestantsHandleRoute
  '/categories/': typeof CategoriesIndexRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/contestants/': typeof ContestantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/auth'
    | '/register'
    | '/sponsors'
    | '/categories/$slug'
    | '/competitions/$slug'
    | '/contestants/$handle'
    | '/categories/'
    | '/competitions/'
    | '/contestants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/auth'
    | '/register'
    | '/sponsors'
    | '/categories/$slug'
    | '/competitions/$slug'
    | '/contestants/$handle'
    | '/categories'
    | '/competitions'
    | '/contestants'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/auth'
    | '/register'
    | '/sponsors'
    | '/categories/$slug'
    | '/competitions/$slug'
    | '/contestants/$handle'
    | '/categories/'
    | '/competitions/'
    | '/contestants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuthRoute: typeof AuthRoute
  RegisterRoute: typeof RegisterRoute
  SponsorsRoute: typeof SponsorsRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CompetitionsSlugRoute: typeof CompetitionsSlugRoute
  ContestantsHandleRoute: typeof ContestantsHandleRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
  ContestantsIndexRoute: typeof ContestantsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/competitions'
      fullPath: '/competitions/'
      preLoaderRoute: typeof CompetitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$slug': {
      id: '/competitions/$slug'
      path: '/competitions/$slug'
      fullPath: '/competitions/$slug'
      preLoaderRoute: typeof CompetitionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contestants/': {
      id: '/contestants/'
      path: '/contestants'
      fullPath: '/contestants/'
      preLoaderRoute: typeof ContestantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contestants/$handle': {
      id: '/contestants/$handle'
      path: '/contestants/$handle'
      fullPath: '/contestants/$handle'
      preLoaderRoute: typeof ContestantsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AuthRoute: AuthRoute,
  RegisterRoute: RegisterRoute,
  SponsorsRoute: SponsorsRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CompetitionsSlugRoute: CompetitionsSlugRoute,
  ContestantsHandleRoute: ContestantsHandleRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
  ContestantsIndexRoute: ContestantsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
